/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface CustomerResponse {
  address?: Address;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
}
