/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderResponse {
  customerId?: string;
  id?: number;
  paymentMethod?: 'PAYPAL' | 'CREDIT_CARD' | 'VISA' | 'MASTER_CARD' | 'BITCOIN';
  reference?: string;
  totalAmount?: number;
}
