/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseRequest } from '../models/purchase-request';
export interface OrderRequest {
  customerId: string;
  id?: number;
  paymentMethod: 'PAYPAL' | 'CREDIT_CARD' | 'VISA' | 'MASTER_CARD' | 'BITCOIN';
  products: Array<PurchaseRequest>;
  reference?: string;
  totalAmount?: number;
}
