/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerResponse } from '../models/customer-response';
export interface PaymentRequest {
  amount?: number;
  customer?: CustomerResponse;
  id?: number;
  orderId?: number;
  orderReference?: string;
  paymentMethod?: 'PAYPAL' | 'CREDIT_CARD' | 'VISA' | 'MASTER_CARD' | 'BITCOIN';
}
