/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  availableQuantity?: number;
  categoryDescription?: string;
  categoryId?: number;
  categoryName?: string;
  description?: string;
  id?: number;
  imageUrl?: string;
  name?: string;
  price?: number;
}
