/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ManagementService } from './services/management.service';
import { CustomerControllerService } from './services/customer-controller.service';
import { AdminControllerService } from './services/admin-controller.service';
import { ProductControllerService } from './services/product-controller.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { OrderControllerService } from './services/order-controller.service';
import { AuthenticationService } from './services/authentication.service';
import { UserControllerService } from './services/user-controller.service';
import { OrderLineControllerService } from './services/order-line-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ManagementService,
    CustomerControllerService,
    AdminControllerService,
    ProductControllerService,
    PaymentControllerService,
    OrderControllerService,
    AuthenticationService,
    UserControllerService,
    OrderLineControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
