/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createCustomer } from '../fn/customer-controller/create-customer';
import { CreateCustomer$Params } from '../fn/customer-controller/create-customer';
import { CustomerResponse } from '../models/customer-response';
import { deleteCustomer1 } from '../fn/customer-controller/delete-customer-1';
import { DeleteCustomer1$Params } from '../fn/customer-controller/delete-customer-1';
import { existsById } from '../fn/customer-controller/exists-by-id';
import { ExistsById$Params } from '../fn/customer-controller/exists-by-id';
import { fimdById } from '../fn/customer-controller/fimd-by-id';
import { FimdById$Params } from '../fn/customer-controller/fimd-by-id';
import { findAll2 } from '../fn/customer-controller/find-all-2';
import { FindAll2$Params } from '../fn/customer-controller/find-all-2';
import { updateCustomer } from '../fn/customer-controller/update-customer';
import { UpdateCustomer$Params } from '../fn/customer-controller/update-customer';

@Injectable({ providedIn: 'root' })
export class CustomerControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAll2()` */
  static readonly FindAll2Path = '/api/v1/management/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAll2()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll2$Response(params?: FindAll2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerResponse>>> {
    return findAll2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAll2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll2(params?: FindAll2$Params, context?: HttpContext): Observable<Array<CustomerResponse>> {
    return this.findAll2$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CustomerResponse>>): Array<CustomerResponse> => r.body)
    );
  }

  /** Path part for operation `updateCustomer()` */
  static readonly UpdateCustomerPath = '/api/v1/management/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer$Response(params: UpdateCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer(params: UpdateCustomer$Params, context?: HttpContext): Observable<void> {
    return this.updateCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createCustomer()` */
  static readonly CreateCustomerPath = '/api/v1/management/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCustomer$Response(params: CreateCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCustomer(params: CreateCustomer$Params, context?: HttpContext): Observable<string> {
    return this.createCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `fimdById()` */
  static readonly FimdByIdPath = '/api/v1/management/customers/{customer-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `fimdById()` instead.
   *
   * This method doesn't expect any request body.
   */
  fimdById$Response(params: FimdById$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerResponse>> {
    return fimdById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `fimdById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  fimdById(params: FimdById$Params, context?: HttpContext): Observable<CustomerResponse> {
    return this.fimdById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerResponse>): CustomerResponse => r.body)
    );
  }

  /** Path part for operation `deleteCustomer1()` */
  static readonly DeleteCustomer1Path = '/api/v1/management/customers/{customer-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCustomer1()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer1$Response(params: DeleteCustomer1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCustomer1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCustomer1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer1(params: DeleteCustomer1$Params, context?: HttpContext): Observable<void> {
    return this.deleteCustomer1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `existsById()` */
  static readonly ExistsByIdPath = '/api/v1/management/customers/exists/{customer-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `existsById()` instead.
   *
   * This method doesn't expect any request body.
   */
  existsById$Response(params: ExistsById$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return existsById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `existsById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  existsById(params: ExistsById$Params, context?: HttpContext): Observable<boolean> {
    return this.existsById$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
